### ISSUE TITLE
Dataset subset to examine

### ISSUE THREAD

**Issue by justachetan** [RuiningLi/puppet-master#3]
Hello again @RuiningLi ! :D 

Congrats on the amazing work!

Is there a pre-rendered dataset subset of the Objaverse-HQ available for download that I can use to examine the results of the rendering script?

**Comment by RuiningLi** [comment]
Hi @justachetan,

I uploaded 5 instances under https://github.com/RuiningLi/puppet-master/blob/main/data/examples.zip.
